apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-boot-k8s-demo
  name: spring-boot-k8s-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-k8s-demo
  template:
    metadata:
      labels:
        app: spring-boot-k8s-demo
    spec:
      containers:
      - image: pseudojo/spring-boot-dockerize-test:0.0.1
        name: spring-boot-dockerize-test
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /home/app/application.properties
          subPath: application.properties
          name: spring-boot-config
      terminationGracePeriodSeconds: 5
      volumes:
      - name: spring-boot-config
        secret:
         secretName: spring-boot-k8s-demo
         defaultMode: 0440
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-boot-k8s-demo
  name: spring-boot-k8s-demo
spec:
  ports:
  - name: boot-port
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-boot-k8s-demo
  type: NodePort
---
kind: Secret
apiVersion: v1
metadata:
  name: spring-boot-k8s-demo
data:
  application.properties: c2VydmVyLnBvcnQ9ODA4MAoKY3VzdG9tLm15bmFtZT1HaWxkb25nIEhvbmcKY3VzdG9tLm15YWdlPTQ5CmN1c3RvbS5teXRlbD0wMTA0OTQ5ODk4OQoK

---